name = "moving-box-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[durable_objects.bindings]]
name = "BOX_STATE"
class_name = "BoxRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["BoxRoom"]

[[kv_namespaces]]
binding = "USER_CACHE"
id = "99a16a9978634ff194b9c91350a7c1bb"
preview_id = "99a16a9978634ff194b9c91350a7c1bb"

[env.production]
workers_dev = false